import type { ExperienceEntry } from './experience-timeline.types';

export const EXPERIENCE_ENTRIES: ExperienceEntry[] = [
	{
		id: '39091b0c-0778-4a49-8b6d-ce416651a2d6',
		date_range: 'Aug 2025 — Present',
		company: 'Actum Digital',
		job_title: 'Senior Frontend Developer',
		location: 'Prague',
		highlights: [
			'Integrated Auth0 SDK with several frontend applications in Next.js and legacy applications',
		],
		stack: ['React', 'Next.js', 'TypeScript', 'Storybook'],
		is_current: true,
	},
	{
		id: 'd8e02b85-1970-4eaf-b82b-55ca1ec6ae4f',
		date_range: 'Apr 2021 — Jul 2025',
		company: 'Innovatrics',
		location: 'Bratislava',
		job_title: 'Software Engineer',
		highlights: [
			'Led the development of multiple React web applications focused on enrollment, modification (editor), and preview of biometric data and applicant information within a monorepo setup using Turborepo',
			'Built a scalable design system on top of Radix UI to enhance project consistency',
			'As a Frontend Guild Lead I coordinated frontend tech strategies, mentored developers across two product teams and contributed to hiring and interviews',
			'Organized bi-weekly Frontend Coffee meetings to discuss new frontend topics',
			'Wrote coding guidelines, maintained lint and formatting rules',
		],
		stack: [
			'React',
			'TypeScript',
			'Radix UI',
			'Stitches',
			'GraphQL',
			'TanStack',
			'Redux Toolkit',
			'Recoil',
			'Turborepo',
			'Storybook',
		],
	},
	{
		id: 'c9b8e8ed-e193-4b45-98e0-29cfb4352c84',
		date_range: 'May 2020 — Mar 2021',
		company: 'ISDD plus',
		location: 'Bratislava',
		job_title: 'Senior Frontend Developer',
		highlights: [
			'Built a React dashboard for Slovanet to manage IoT devices',
			'Developed the redesigned My Orange web application',
			'Coordinated junior frontend developers and ensured code quality through reviews',
		],
		stack: ['React', 'TypeScript', 'Material UI', 'Cypress', 'Sass'],
	},
	{
		id: '94a6768a-fa3f-4362-a269-67365582615d',
		date_range: 'Dec 2019 — Jan 2020',
		company: 'Boardie startup',
		location: 'Prague',
		job_title: 'Freelance',
		highlights: [
			'Developed a React application for internal company presentations, featuring employee profiles, events, news, and other information',
		],
		stack: [
			'React',
			'TypeScript',
			'Styled Components',
			'Framer Motion',
			'Next.js',
		],
	},
	{
		id: '8abfc07f-7847-471a-a51d-be16562307ad',
		date_range: 'Aug 2018 — Apr 2020',
		company: 'Creative Dock',
		location: 'Prague',
		job_title: 'React Developer',
		highlights: [
			'Led frontend development of a React web app for online loans at Wustenrot, overseeing and assigning tasks to two other developers',
		],
		stack: ['React', 'Flow', 'Styled Components', 'Redux'],
	},
	{
		id: '320e1114-cd99-4f1f-b089-b6d7be2fec22',
		date_range: 'Jul 2015 — Aug 2018',
		company: 'Actum Digital',
		location: 'Prague',
		job_title: 'Frontend / Senior Frontend Developer',
		highlights: [
			'Worked on international projects for companies like Metro Cash & Carry, Wustenrot, Walmark, and Zindulka (Yachting.com) in an Agile (Scrum) environment, while also contributing to internal projects like Actum UI Kit and Actum Dev Stack',
			'Estimated new project scopes and led frontend development for Walmark’s Eshop solution klubzdravi.cz, creating HTML templates for Kentico CMS, managing junior developers, and conducting code reviews',
			'Developed for walmark.cz, creating HTML templates for Kentico CMS and a React-based Health Index application, and optimized the Gulp dev stack using Webpack',
		],
		stack: [
			'Nunjucks',
			'Sass',
			'JavaScript',
			'React',
			'Flow',
			'Redux',
			'Gulp',
			'Webpack',
		],
	},
	{
		id: '41bcf6c8-d944-457d-8a07-c5fb52a4b0d1',
		date_range: 'Oct 2011 — Jan 2017',
		company:
			'Dry Con / Pricewise (Bratislava), G2G Online (Netherlands), Mega (Prague)',
		location: '',
		job_title: 'Freelance',
		highlights: [
			'Built static websites and managed content for WordPress / On Target CMS',
			'Customized WordPress themes based on provided designs',
		],
		stack: ['HTML', 'CSS', 'jQuery', 'WordPress', 'Nunjucks'],
	},
];
